Repository StoPlay/stoplay-ext, pull requests merged in 2018-10, with the labels that each got.

#112 Spotify: new player UI and subdomain
  background.js
  content.js
Labels: bug, hacktoberfest

#110 udemy.com: Added support
  README.md
  background.js
  content.js
Labels: hacktoberfest, service-request

#111 megogo.net: Fixed support
  README.md
  background.js
  content.js
Labels: bug, hacktoberfest

#116 Migrated all statuses to status types
  content.js
Labels: tech
